### ISSUE TITLE
Status Webhook always flags delivered

### ISSUE THREAD

**Issue by jonny-no1** [fourlabsldn/PlivoBundle#3]
The status webhook is called with the status of the message including "queued", "sent", "failed", "delivered", "undelivered" or "rejected". The correct status along with units and error code should be saved.

The URL to which with the status of the message is sent. The following parameters are sent to the URL:
**To** - Phone number of the recipient
**From** - Phone number of the sender
**Status** - Status of the message including "queued", "sent", "failed", "delivered", "undelivered" or "rejected"
...
**Units** - Number of units into which a long SMS was split
**ErrorCode** - Delivery Response code returned by the carrier attempting the delivery. See Supported error codes below.

https://www.plivo.com/docs/api/message/

**Comment by galeaspablo** [comment]
Resolved by 53d3bbb9f806fa394c03d8c016bcdc7f3ed97ae1
